package nekouidaga.net.familyheartplugin.database
import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import org.bukkit.configuration.file.FileConfiguration
import java.sql.Connection
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors
import java.util.logging.Logger
class DatabaseManager(private val log:Logger){private lateinit var ds:HikariDataSource;val executor:ExecutorService=Executors.newFixedThreadPool(8){Thread(it,"FamilyHeart-DB").apply{isDaemon=true}}
fun connect(c:FileConfiguration){ds=HikariDataSource(HikariConfig().apply{jdbcUrl="jdbc:mysql://${c.getString("mysql.host","localhost")}:${c.getInt("mysql.port",3306)}/${c.getString("mysql.database","familyheart")}?useSSL=${c.getBoolean("mysql.useSSL",false)}&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC";username=c.getString("mysql.username","familyheart");password=c.getString("mysql.password","");maximumPoolSize=c.getInt("mysql.pool.maximum-pool-size",10);minimumIdle=c.getInt("mysql.pool.minimum-idle",2);connectionTimeout=c.getLong("mysql.pool.connection-timeout-ms",10000);poolName="FamilyHeart-Pool"});initSchema()}
fun connection():Connection=ds.connection
private fun initSchema(){listOf("CREATE TABLE IF NOT EXISTS players(uuid VARCHAR(36) PRIMARY KEY,mcid VARCHAR(32) NOT NULL,first_seen TIMESTAMP NOT NULL,last_seen TIMESTAMP NOT NULL,INDEX idx_mcid(mcid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS relationship_sequence(id BIGINT NOT NULL PRIMARY KEY) ENGINE=InnoDB","CREATE TABLE IF NOT EXISTS relationships(internal_id BIGINT AUTO_INCREMENT PRIMARY KEY,relationship_id VARCHAR(32) UNIQUE NOT NULL,player_a VARCHAR(36) NOT NULL,player_b VARCHAR(36) NOT NULL,type VARCHAR(32) NOT NULL,role_a VARCHAR(32) NOT NULL,role_b VARCHAR(32) NOT NULL,auto_added BOOLEAN NOT NULL DEFAULT FALSE,status VARCHAR(16) NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,INDEX idx_a(player_a,status),INDEX idx_b(player_b,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS relationship_history(id BIGINT AUTO_INCREMENT PRIMARY KEY,relationship_id VARCHAR(32) NOT NULL,action VARCHAR(64) NOT NULL,actor VARCHAR(36),target VARCHAR(36),reason TEXT,created_at TIMESTAMP NOT NULL,INDEX idx_hist(relationship_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS requests(id BIGINT AUTO_INCREMENT PRIMARY KEY,requester VARCHAR(36) NOT NULL,target VARCHAR(36) NOT NULL,type VARCHAR(32) NOT NULL,metadata TEXT,status VARCHAR(16) NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,INDEX idx_req_target(target,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS actions(id BIGINT AUTO_INCREMENT PRIMARY KEY,actor VARCHAR(36) NOT NULL,target VARCHAR(36) NOT NULL,action VARCHAR(32) NOT NULL,created_at TIMESTAMP NOT NULL,INDEX idx_actions(actor,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS family_penalties(id BIGINT AUTO_INCREMENT PRIMARY KEY,target_type VARCHAR(16) NOT NULL,target_player VARCHAR(36),target_relationship VARCHAR(32),effect VARCHAR(64) NOT NULL,value DOUBLE NOT NULL,multiplier DOUBLE NOT NULL DEFAULT 1,started_at TIMESTAMP NOT NULL,ends_at TIMESTAMP NULL,removable BOOLEAN NOT NULL DEFAULT TRUE,active BOOLEAN NOT NULL DEFAULT TRUE,INDEX idx_pen_player(target_player,active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS audit_log(id BIGINT AUTO_INCREMENT PRIMARY KEY,actor VARCHAR(36),action VARCHAR(64) NOT NULL,target_player VARCHAR(36),relationship_id VARCHAR(32),result VARCHAR(16) NOT NULL,reason TEXT,created_at TIMESTAMP NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4").forEach { sql -> connection().use { conn -> conn.createStatement().use { st -> st.executeUpdate(sql) } } }}
fun shutdown(){if(::ds.isInitialized)ds.close();executor.shutdownNow()}}
inline fun <T> Connection.tx(block:(Connection)->T):T{val ac=autoCommit;autoCommit=false;return try{val v=block(this);commit();v}catch(e:Exception){rollback();throw e}finally{autoCommit=ac}}
